# ! FOR SUCCESSFUL TESTING, IF PORT HAS BEEN CHANGED, 
# ! MAKE SURE TO MODIFY PORTS ON OTHER TESTING FILE
@port = 8080
@baseUrl = https://bottlebot.onrender.com/api

### * test route to send value of led to monitor
POST {{baseUrl}}/monitor
Content-Type: application/json

{
  "value": 5
}

### * for overflow
POST {{baseUrl}}/monitor
Content-Type: application/json

{
  "overflowLevel": "90"
}

### * for overflow
POST {{baseUrl}}/monitor
Content-Type: application/json

{
  "batteryLevel": "30"
}

### * for orientation
POST {{baseUrl}}/monitor
Content-Type: application/json

{
  "orientation": "0",
  "waterLevel": "90",
  "overflowLevel": "10",
  "batteryLevel": "100",
  "arrived": "true",
  "arrivedAt": "6755a3b9fdc887113268ca12"
}

### * if moving or not
POST {{baseUrl}}/monitor
Content-Type: application/json

{
  "traveling": true
}