# ! FOR SUCCESSFUL TESTING, IF PORT HAS BEEN CHANGED, 
# ! MAKE SURE TO MODIFY PORTS ON OTHER TESTING FILE
@port = 8080
@baseUrl = http://localhost:{{port}}/api

### * test route to send value of led to monitor
POST {{baseUrl}}/monitor
Content-Type: application/json

{
  "value": 5
}

### * for overflow
POST {{baseUrl}}/monitor
Content-Type: application/json

{
  "overflowLevel": "10%"
}

### * for overflow
POST {{baseUrl}}/monitor
Content-Type: application/json

{
  "waterLevel": "0%"
}

### * for orientation
POST {{baseUrl}}/monitor
Content-Type: application/json

{
  "orientation": 1
}

### * if moving or not
POST {{baseUrl}}/monitor
Content-Type: application/json

{
  "traveling": true
}