# ! FOR SUCCESSFUL TESTING, IF PORT HAS BEEN CHANGED, 
# ! MAKE SURE TO MODIFY PORTS ON OTHER TESTING FILE
@port = 8080
@baseUrl = http://localhost:{{port}}/api

### * test route 1 for adding bottle disposal history
POST {{baseUrl}}/history/dispose
Content-Type: application/json

{
  "userId": "66fb133aff0811b349be131c",
  "bottleCount": 1,
  "pointsAccumulated": 2
}

### * test route 2 for adding bottle disposal history
POST {{baseUrl}}/history/dispose
Content-Type: application/json

{
  "userId": "66ed98453aa56d8e612b209b",
  "bottleCount": 1,
  "pointsAccumulated": 1
}

### * test route for getting all users disposal history
GET {{baseUrl}}/history/dispose

### * test route for getting all users with name filter
GET {{baseUrl}}/history/dispose?userName=Josh

### * test route for getting one user disposal history
GET {{baseUrl}}/history/dispose/66ed98453aa56d8e612b209b

### * test route for updating bottle disposal history
PUT {{baseUrl}}/history/dispose/66f00533e85eb1c23ded9b2f
Content-Type: application/json

{
  "userId": "66ed98453aa56d8e612b209b",
  "bottleCount": 3,
  "pointsAccumulated": 3
}

### * test route for removing bottle disposal history
DELETE {{baseUrl}}/history/dispose/66ef08b46b6630441b343450

### * test route for removing bottle disposal history per user
DELETE {{baseUrl}}/history/dispose/all/66ed98453aa56d8e612b209b

### * test route for getting one user total bottle dispose
GET {{baseUrl}}/history/dispose/bottle/66ed98453aa56d8e612b209b

# * PAGINATIONS
### * test route for all users bottle disposal pagination
GET {{baseUrl}}/history/dispose?page=1&limit=1

### * test route for all users bottle disposal pagination based on user name
GET {{baseUrl}}/history/dispose?userName=Staff&page=1&limit=1

### * test route for one user disposal history pagination
GET {{baseUrl}}/history/dispose/67164816e226d5fe58818645?page=1&limit=1

# * ARCHIVING
### * archive 1 disposed bottle record, same route on deleting
DELETE {{baseUrl}}/history/dispose/6723575916bbcb387402665b

### * getting all users archived bottle disposal record only
GET {{baseUrl}}/history/dispose?status=archived

### * getting one user archived bottle disposal record only
GET {{baseUrl}}/history/dispose/6723575916bbcb387402665b

### * getting all users active bottle disposal record only
GET {{baseUrl}}/history/dispose?status=active

### * unarchive bottle disposal record
PUT {{baseUrl}}/history/dispose/6723575916bbcb387402665b
Content-Type: application/json

{
  "userId": "66ed98453aa56d8e612b209b",
  "bottleCount": 3,
  "pointsAccumulated": 3,
  "archiveDate": null
}