# ! FOR SUCCESSFUL TESTING, IF PORT HAS BEEN CHANGED, 
# ! MAKE SURE TO MODIFY PORTS ON OTHER TESTING FILE
@port = 8080
@baseUrl = http://localhost:{{port}}/api

### * test1 request to queue for bot navigation
POST {{baseUrl}}/queue
Content-Type: application/json

{
  "returnToDefault" : "true"
}

### * test2 request to queue for bot navigation
POST {{baseUrl}}/queue
Content-Type: application/json

{
  "userId" : "67164816e226d5fe58818645",
  "location": {
    "lon" : 120.9766973,
    "lat" : 14.648316,
    "locationName" : "Dyan lang sa gedli :)"
  },
  "status" : "pending"
}

### * test request to remove location queue for finished navigation
# * NOTE U NEED THE QUEUE ID HERE NOT USER ID
DELETE {{baseUrl}}/queue/66fed3c373a269ad64fd9c56