# ! FOR SUCCESSFUL TESTING, IF PORT HAS BEEN CHANGED, 
# ! MAKE SURE TO MODIFY PORTS ON OTHER TESTING FILE
@port = 8080
@baseUrl = http://localhost:{{port}}/api

### * test route 1 for adding rewards claimed history
POST {{baseUrl}}/history/claim
Content-Type: application/json

{
  "userId": "66fb133aff0811b349be131c",
  "rewardId": "66f6e76bc6fa1bb4916d67e8"
}

# "pointsSpent": 1

### * test route 2 for adding rewards claimed history
POST {{baseUrl}}/history/claim
Content-Type: application/json

{
  "userId": "66ed98453aa56d8e612b209b",
  "rewardId": "66f6e76bc6fa1bb4916d67e8"
}

# "pointsSpent": 1

### * test route for getting all users reward claim history
GET {{baseUrl}}/history/claim

### * test route for getting all users reward claim history based on user name
GET {{baseUrl}}/history/claim?userName=Citizen

### * test route for getting one user reward claim history
GET {{baseUrl}}/history/claim/user/67225a62ba9e3dea6540a422

### * test route for getting one unique reward claim history
GET {{baseUrl}}/history/claim/672856ebb6889caba5bb832e

### * test route for updating reward claim history
PUT {{baseUrl}}/history/claim/66ef1373265204a3d62c53d5
Content-Type: application/json

{
  "userId": "66ed98453aa56d8e612b209b",
  "rewardId": "66eefacb3479f08d051566f6"
}

# "pointsSpent": 3

### * test route for removing reward claim history
DELETE {{baseUrl}}/history/claim/66ef0ef8f1634b06d18fc9cf

### * test route for removing reward claim history per user
DELETE {{baseUrl}}/history/claim/all/66eda9be5bd1b94d69bddfcc

### * test route for getting one user current points
GET {{baseUrl}}/history/claim/points/66ed98453aa56d8e612b209b


### * PAGINATIONS
### * test route for all users reward claim pagination
GET {{baseUrl}}/history/claim?page=1&limit=1

### * test route for all users reward claim pagination based on user name
GET {{baseUrl}}/history/claim?userName=Citizen&page=1&limit=1

### * test route for one user reward claim pagination
GET {{baseUrl}}/history/claim/67164816e226d5fe58818645?page=1&limit=1

### * ARCHIVING
### * archive 1 claim reward record, same route on deleting
DELETE {{baseUrl}}/history/claim/67236805fe441291a9d33cda

### * unarchive 1 claim reward record, same route on update
PUT {{baseUrl}}/history/claim/67236805fe441291a9d33cda
Content-Type: application/json

{
  "archiveDate": null,
  "userId": "67164816e226d5fe58818645",
  "rewardId": "67233d04bb0b9f13f8cd2a22",
  "pointsSpent": 1
}

### * getting all users archived claim reward record only
GET {{baseUrl}}/history/claim?status=archived

### * getting one user archived claim reward record only
GET {{baseUrl}}/history/claim/67164816e226d5fe58818645?status=archived

### * getting all users active claim reward record only
GET {{baseUrl}}/history/claim?status=active

### * getting one user active claim reward record only
GET {{baseUrl}}/history/claim/67164816e226d5fe58818645?status=active