# ! FOR SUCCESSFUL TESTING, IF PORT HAS BEEN CHANGED, 
# ! MAKE SURE TO MODIFY PORTS ON OTHER TESTING FILE
@port = 8080
@baseUrl = http://localhost:{{port}}/api

### * test route to get all users
GET {{baseUrl}}/users/

### * test route to get one user
GET {{baseUrl}}/users/66ed7df69271160de05cbd59


### * test route to filter user by level
GET {{baseUrl}}/users?level=citizen

### * test route to filter user by name (first, middle, and last)
# * (no filter for fullname or fname+mName or fname+lname)
GET {{baseUrl}}/users?userName=Josh

### * test route for register
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "personalInfo": {
    "firstName": "Jiwo",
    "middleName": "G",
    "lastName": "Mendador",
    "dateOfBirth": "1990-01-01",
    "gender": "Male",
    "civilStatus": "Single",
    "nationality": "Filipino"
  },
  "contactInfo": {
    "address": {
      "houseNumber": "123",
      "street": "Main St",
      "barangay": "Barangay 1",
      "city": "City Name"
    },
    "phoneNumbers": ["09123456789"]
  },
  "economicInfo": {
    "employmentStatus": "Employed",
    "occupation": "Engineer"
  },
  "credentials": {
    "email": "user3@example.com",
    "password": "yourpassword3"
  }
}

### * test route for updating user
PUT {{baseUrl}}/users/66ed98183aa56d8e612b2097
Content-Type: application/json

{
  "personalInfo": {
    "firstName": "John",
    "middleName": "Doe",
    "lastName": "Smith",
    "dateOfBirth": "1990-01-01",
    "gender": "Male",
    "civilStatus": "Single",
    "nationality": "Filipino"
  },
  "contactInfo": {
    "address": {
      "houseNumber": "123",
      "street": "Main St",
      "barangay": "Barangay 1",
      "city": "City Name"
    },
    "phoneNumbers": ["09123456798"]
  },
  "economicInfo": {
    "employmentStatus": "Employed",
    "occupation": "Engineer"
  },
  "credentials": {
    "email": "user@example.com",
    "password": "yourpassword"
  }
}

### * test route for deleting user
DELETE {{baseUrl}}/users/66ed98183aa56d8e612b2097


### * FOR PAGINATION !!!!
### * test route for pagination default page and default limit (number of items)
GET {{baseUrl}}/users?page=1&limit=3
### * test route for pagination with a filter
GET {{baseUrl}}/users?userName=User&page=1&limit=3

### * LOGIC
### * declare a var for currentPage
### * optionally, if you want to control the number of items to get 
### *   declare a var for limit

### * when user click on next page, increment the page number (page++ or page += 1) 
### * when user click on prev page, decrement the page number (page-- or page -= 1)
### * when user clicks directly on the page number, 
### *   just set the current page on that number (page = userClickedPage)
### * dont forget the validations (current page number >= 1) 
### *   and (currentpage number <= totalAvailablePages)