# ! FOR SUCCESSFUL TESTING, IF PORT HAS BEEN CHANGED, 
# ! MAKE SURE TO MODIFY PORTS ON OTHER TESTING FILE
@port = 8080
@baseUrl = http://localhost:{{port}}/api

### * test route to get all users
GET {{baseUrl}}/users/

### * test route to get one user
GET {{baseUrl}}/users/66ed7df69271160de05cbd59


### * test route to filter user by level
GET {{baseUrl}}/users?level=citizen&limit=2&page=4

### * test route to filter user by name (first, middle, and last)
# * (no filter for fullname or fname+mName or fname+lname)
GET {{baseUrl}}/users?userName=Josh

### * test route for register
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "personalInfo": {
    "firstName": "Jiwo",
    "middleName": "G",
    "lastName": "Mendador",
    "dateOfBirth": "1990-01-01",
    "gender": "Male",
    "civilStatus": "Single",
    "nationality": "Filipino"
  },
  "contactInfo": {
    "address": {
      "houseNumber": "123",
      "street": "Main St",
      "barangay": "Barangay 1",
      "city": "City Name"
    },
    "phoneNumbers": ["09123456789"]
  },
  "economicInfo": {
    "employmentStatus": "Employed",
    "occupation": "Engineer"
  },
  "credentials": {
    "email": "user3@example.com",
    "password": "yourpassword3"
  }
}

### * test route for updating user
PUT {{baseUrl}}/users/66ed98183aa56d8e612b2097
Content-Type: application/json

{
  "personalInfo": {
    "firstName": "John",
    "middleName": "Doe",
    "lastName": "Smith",
    "dateOfBirth": "1990-01-01",
    "gender": "Male",
    "civilStatus": "Single",
    "nationality": "Filipino"
  },
  "contactInfo": {
    "address": {
      "houseNumber": "123",
      "street": "Main St",
      "barangay": "Barangay 1",
      "city": "City Name"
    },
    "phoneNumbers": ["09123456798"]
  },
  "economicInfo": {
    "employmentStatus": "Employed",
    "occupation": "Engineer"
  },
  "credentials": {
    "email": "user@example.com",
    "password": "yourpassword"
  }
}

### * test route for deleting user
DELETE {{baseUrl}}/users/66ed98183aa56d8e612b2097


### * FOR PAGINATION !!!!
### * test route for pagination default page and default limit (number of items)
GET {{baseUrl}}/users?page=1&limit=3
### * test route for pagination with a filter
GET {{baseUrl}}/users?userName=User&page=1&limit=3

### * PAGINATION LOGIC
### * declare a var for currentPage
### * optionally, if you want to control the number of items to get 
### *   declare a var for limit

### * when user click on next page, increment the page number (page++ or page += 1) 
### * when user click on prev page, decrement the page number (page-- or page -= 1)
### * when user clicks directly on the page number, 
### *   just set the current page on that number (page = userClickedPage)
### * dont forget the validations (current page number >= 1) 
### *   and (currentpage number <= totalAvailablePages)

### * FOR ARCHIVING !!!
### * test route for getting all users that's been archived
GET {{baseUrl}}/users?status=archived
### * test route for getting all users that's still active
GET {{baseUrl}}/users?status=active
### * test route for getting all users (both active or archived)
### * still the same on the prev way
GET {{baseUrl}}/users?page=1
### * test route to archive a user (still the same on prev like deleting it)
DELETE {{baseUrl}}/users/6716478ae226d5fe5881863c
### * test route to unarchive a user
PUT {{baseUrl}}/users/6716478ae226d5fe5881863c
Content-Type: application/json

{
  "archiveDate": null,
  "personalInfo": {
    "firstName": "John",
    "middleName": "Doe",
    "lastName": "Smith",
    "dateOfBirth": "1990-01-01",
    "gender": "Male",
    "civilStatus": "Single",
    "nationality": "Filipino"
  },
  "contactInfo": {
    "address": {
      "houseNumber": "123",
      "street": "Main St",
      "barangay": "Barangay 1",
      "city": "City Name"
    },
    "phoneNumbers": ["09123456798"]
  },
  "economicInfo": {
    "employmentStatus": "Employed",
    "occupation": "Engineer"
  },
  "credentials": {
    "email": "user@example.com",
    "password": "yourpassword"
  }
}

### * ARCHIVING LOGIC
### * a filter button to see only active users, or only archived users, or also both
### * no archiveDate in adding of user, 
### *   archiveDate only triggers when remove button is clicked
### * what if you want to unarchive or want to update the date that it is archived?
### *   on the update page of the user, archiveDate is editable (date picker) ONLY IF archive date is not null 
### *   pick a date to remain it as archived, remove the date or set to null to unarchive